# Generated by Django 4.2.4 on 2024-03-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='departments.department'),
            preserve_default=False,
        ),
    ]
