# Generated by Django 4.2.4 on 2024-03-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
