# Generated by Django 4.2.4 on 2024-03-25 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_requestnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnotification',
            name='user_submitted_notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_submitted_notification', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
