# Generated by Django 4.2.4 on 2024-03-27 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0006_alter_requestnotification_user_submitted_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestnotification',
            name='user_submitted_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_submitted_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
