# Generated by Django 4.2.4 on 2024-03-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_status_alter_request_urgency'),
        ('notifications', '0002_remove_requestnotification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestnotification',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.request'),
        ),
    ]
