# Generated by Django 4.2.4 on 2024-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_requestnotification_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnotification',
            name='notification_type',
            field=models.CharField(choices=[('Request', 'Request'), ('User', 'User')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
