# Generated by Django 4.2.4 on 2024-03-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_eligible_for_staff',
        ),
    ]
