# Generated by Django 4.2.4 on 2024-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_role_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
