# Generated by Django 4.2.4 on 2024-03-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skip_initial_profile_details',
            field=models.BooleanField(default=False),
        ),
    ]
