# Generated by Django 4.2.4 on 2024-03-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestnotification',
            name='is_read',
        ),
    ]
