# Generated by Django 4.2.4 on 2024-03-15 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0004_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='worked_on_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worked_on_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
