# Generated by Django 4.2.4 on 2024-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_last_updated_by_request_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved')], default='Waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10),
        ),
    ]
