# Generated by Django 4.2.4 on 2024-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_request_last_updated_by_alter_request_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='urgency',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10, null=True),
        ),
    ]
