# Generated by Django 4.2.4 on 2024-03-09 21:29

from django.db import migrations
from django.db.migrations import RunPython

def initialize_departments(apps, schema_editor):
        Department = apps.get_model('departments', 'Department')
        default_departments = {
            'IT': 'Brief IT description',
            'Customer Support': 'Brief CS description',
            'Engineering': 'Brief engineering description',
            'Marketing': 'Brief marketing description',
        }

        for department_name, description in default_departments.items():
            Department.objects.create(name=department_name, description=description)


class Migration(migrations.Migration):


    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        RunPython(initialize_departments),
    ]
